# Generated by Django 5.2.1 on 2025-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamall', '0002_hireitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireitem',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
