# Generated by Django 5.2.3 on 2025-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("megamall", "0003_hireitem_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcel_action",
                    models.CharField(
                        choices=[("send", "Send"), ("receive", "Receive")],
                        max_length=10,
                    ),
                ),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                ("selected_item", models.CharField(max_length=100)),
                ("item_price", models.IntegerField()),
                ("delivery_fee", models.IntegerField()),
                ("total", models.IntegerField()),
                ("payment_method", models.CharField(max_length=50)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("delivery_location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
