# Generated by Django 5.2.3 on 2025-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("megamall", "0004_courierorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierorder",
            name="contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="delivery_fee",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="from_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="item_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="recipient_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="selected_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="to_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courierorder",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
