# Generated by Django 5.2.3 on 2025-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("megamall", "0005_alter_courierorder_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierorder",
            name="item_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="courierorder",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[("send", "Send"), ("receive", "Receive")],
                max_length=10,
                null=True,
            ),
        ),
    ]
