# Generated by Django 5.2.4 on 2025-08-01 02:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamall', '0006_courierorder_item_type_courierorder_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
