# Generated by Django 5.2.4 on 2025-08-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamall', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireitem',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
